assignment8, start daemon change

diff --git a/server/aesdsocket-start-stop b/server/aesdsocket-start-stop
--- a/server/aesdsocket-start-stop
+++ b/server/aesdsocket-start-stop
@@ -3,7 +3,7 @@
 case "$1" in 
 	start)
 		echo  -n "Starting aesdsocket daemon "
-		start-stop-daemon -S -n aesdsocket -a aesdsocket -- -d && echo " -  Sucessfully started" || echo " -  Failed to start"
+		start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d && echo " -  Sucessfully started" || echo " -  Failed to start"
 		;;
 	stop)
 		echo -n "Stopping aesdsocket daemon "
